### ISSUE TITLE
DOALS LiDAR undistortion

### ISSUE THREAD

**Issue by JoLichtenfeld** [ethz-asl/dynablox#12]
Thank you very much for this well documented work and source code.

I have a question concerning the lidar undistortion for the DOALS sequences. I decided to ask this question here instead of [lidar_undistortion](https://github.com/ethz-asl/lidar_undistortion), though, in hope of a faster answer :)
Maybe I don't understand correctly what the undistortion node is supposed to do. Looking at the cloud that it outputs (topic "/pointcloud"), there are still distortion artefacts visible at the beginning/end of each scan line, see image. 
![doals_distortion](https://github.com/ethz-asl/dynablox/assets/83079078/43e2c2d7-ae3a-43d1-82ce-d93805d085d7)

Am I doing something wrong or is it supposed to look like this? I strictly followed the commands from the Readme running run_experiment.launch. 
The reason I am asking is that I want to project the pointcloud onto a spherical image which is hindered by the distortion.

Thanks!

**Comment by patripfr** [comment]
Hi,
I think your undistortion is working correctly. What you are observing here ("artefacts visible at the beginning/end of each scan line") is actually an expected behaviour and not an artifact of the distortion but the undistortion. In fact, you will see that the distorted / original pointcloud as captured by the sensor is always closed at the beginning/end. 

However, if the sensor is rotating during one sweep, it can happen that it does actually not capture the full 360 degree. This is taken into account by the undistortion module and therefore the lines do not close at the beginning/end.

Regarding your efforts to project the pointcloud onto a spherical image you will achieve (visually) better results when using the distorted pointcloud. In the distorted pointcloud you will always have one point per pixel, while with the undistorted/corrected point cloud it can happen that multiple points fall into one pixel and thus result in black / missing pixels in the image.
