### ISSUE TITLE
grpc complie ??

### ISSUE THREAD

**Issue by maomao0220** [ethz-asl/dynablox#3]
When compiling grpc package is known to be stuck at 12%，what can i do ?
![fd9800dda98cc7b52ddfe041589992f](https://user-images.githubusercontent.com/64572122/234246019-3754dbec-8dce-4733-9081-33a90ef2e69f.png)
![fd9800dda98cc7b52ddfe041589992f](https://user-images.githubusercontent.com/64572122/234246036-5fe6b53e-58c6-4f26-9fd1-3f44ba67b789.png)

**Comment by Schmluk** [comment]
GRPC is a large package that can take time to build, in particular depending on the hardware and number of threads used. We have never encountered this issue in our own or CI builds. Since GRPC is a dependency of ours we can unfortunately not give more detailed insights here.

If it is still compiling then there might be nothing wrong with it but it just takes some time? If it is a known issue then there might be some help out there as well. Otherwise building from scratch (deleting it in the ws/build folder and/or using --force-cmake) can help resolve building issues.

Hope this helps!

**Comment by Schmluk** [comment]
Closed due to inactivity.
