### ISSUE TITLE
Run in real time

### ISSUE THREAD

**Issue by zhangye1111** [ethz-asl/dynablox#30]
Thanks for your excellent work. Now I have an os0-128 LiDAR. I want to receive the point cloud topic of the LiDAR for detection in real time. Which files should I modify? Can you help me? Thank you very much.

**Comment by Schmluk** [comment]
Hi @zhangye1111 

Ouster supplies an ouster-ROS interface IIRC that will then publish your point clouds in ROS. You can modify `run_experimen.launch` and remap the topics to subscribe to the pointcloud. 

Note that dynablox expects posed pointclouds, so you probably want to run you LiDAR SLAM algorithm of choice and perform motion undistortion on the pointcloud before feeding it to dynablox. Hope that helps, much success!

**Comment by zhangye1111** [comment]
> 你好@zhangye1111
> 
> Ouster 提供了一个 ouster-ROS 接口 IIRC，它会在 ROS 中发布您的点云。您可以修改`run_experimen.launch`和重新映射主题以订阅点云。
> 
> 请注意，dynablox 需要摆位点云，因此您可能希望运行所选的 LiDAR SLAM 算法，并在将点云输入 dynablox 之前对其进行运动去畸变。希望这能有所帮助，祝您成功！

Thank you very much for your quick reply. With your help, I successfully implemented the detection of moving targets. But now I have a few new questions to ask you. When a target moves, multiple MarkerArrays will be generated to surround the cluster, and when the moving target is stationary, the MarkerArray is still displayed on rviz and does not disappear. Do you know how to optimize these two problems? I guess the second problem may be related to the display time of the MarkerArray.
![2024-08-13 15-25-05屏幕截图](https://github.com/user-attachments/assets/e43b0130-3b79-4cc3-b2c1-985c9c131653)

**Comment by Schmluk** [comment]
Hi @zhangye1111 ,

There will be one set of markers generated for every detected moving cluster. If a single objects get split into several clusters, this typically means the clusters were too far apart to be merged into a single on. You can adjust the clustering settings in the config. 
If you are referring to the additional information displayed, this can be turned off using the namespaces of the marker message.

W.r.t. your second question, this is due to the fact how our detection mechanism works. If an object moves into previously free space, we consider it a dynamic object. Therefore, even if the object stays still for a short while, because it moved there it will still be detected as a dynamic object. While this can also be considered a strength of dynablox, you could for example compare the distances between observations or overlap with previous bounding boxes to filter out objects that are not currently moving.
Hope this helps!

**Comment by zhangye1111** [comment]
@Schmluk Thank you very much for your answer! I have one last question, what do pts and m in the marker message mean?

**Comment by Schmluk** [comment]
Number of points in the cluster and diameter (I think) of the axis-aligned bounding box. The details are in the code if you need to be sure.
